RIFLE_KR = 300
PISTOL_KR = 300
SHOTGUN_KR = 900
SMG_KR = 300

kill_reward = {
    "Cz" : 100,
    "Deagle" : PISTOL_KR,
    "Dualies" : PISTOL_KR,
    "Five-seven" : PISTOL_KR,
    "Glock" : PISTOL_KR,
    "P2000" : PISTOL_KR,
    "P250" : PISTOL_KR,
    "R8" : PISTOL_KR,
    "Tec-9" : PISTOL_KR,
    "USPS" : PISTOL_KR,
    "AK" : RIFLE_KR,
    "AUG" : RIFLE_KR,
    "AWP" : 100,
    "FAMAS" : RIFLE_KR,
    "Auto" : RIFLE_KR,
    "Galol" : RIFLE_KR,
    "M4A1s" : RIFLE_KR,
    "M4A4" : RIFLE_KR,
    "SG" : RIFLE_KR,
    "Scout" : RIFLE_KR,
    "Mac10" : SMG_KR,
    "MP5" : SMG_KR,
    "MP7" : SMG_KR,
    "MP9" : SMG_KR,
    "Bizon" : SMG_KR,
    "P90" : 300,
    "UMP" : SMG_KR,
    "Sawed-off" : SHOTGUN_KR,
    "Mag7" : SHOTGUN_KR,
    "Nova" : SHOTGUN_KR,
    "XM" : SHOTGUN_KR,
    "M249"  : RIFLE_KR,
    "Negev" : RIFLE_KR
}